namespace Healthcare_MVC.Models
{
   
        public class ErrorViewModel
        {
            // Holds the unique tracking request ID generated by the server framework
            public string? RequestId { get; set; }

            // Evaluation helper property to toggle diagnostic layout sections safely
            public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
        }
    }

