// <auto-generated />
using System;
using HealthcareClinic.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Healthcare_System_AdavanceProgrammingProject.Migrations
{
    [DbContext(typeof(ClinicDbContext))]
    [Migration("20260525160216_te")]
    partial class te
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HealthcareClinic.API.Models.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("DoctorNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentDate = new DateTime(2026, 6, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            DoctorNotes = "Routine cardiovascular follow-up.",
                            PatientId = 1,
                            Specialty = "Cardiology",
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 2,
                            AppointmentDate = new DateTime(2026, 6, 3, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            DoctorNotes = "First general checkup visit.",
                            PatientId = 2,
                            Specialty = "General Practice",
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 3,
                            AppointmentDate = new DateTime(2026, 6, 10, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            DoctorNotes = "",
                            PatientId = 1,
                            Specialty = "General Practice",
                            Status = "Requested"
                        });
                });

            modelBuilder.Entity("HealthcareClinic.API.Models.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DaysOff")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("WorkingHours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DaysOff = "Friday, Saturday",
                            Email = "sarah.ahmed@clinic.com",
                            Name = "Dr. Sarah Ahmed",
                            UserId = 2,
                            WorkingHours = "08:00 - 16:00"
                        },
                        new
                        {
                            Id = 2,
                            DaysOff = "Friday, Saturday",
                            Email = "khalid.nasser@clinic.com",
                            Name = "Dr. Khalid Nasser",
                            UserId = 3,
                            WorkingHours = "09:00 - 17:00"
                        });
                });

            modelBuilder.Entity("HealthcareClinic.API.Models.Entities.DoctorSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorSchedules");
                });

            modelBuilder.Entity("HealthcareClinic.API.Models.Entities.DoctorSpecialization", b =>
                {
                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("SpecializationId")
                        .HasColumnType("int");

                    b.HasKey("DoctorId", "SpecializationId");

                    b.HasIndex("SpecializationId");

                    b.ToTable("DoctorSpecializations");

                    b.HasData(
                        new
                        {
                            DoctorId = 1,
                            SpecializationId = 1
                        },
                        new
                        {
                            DoctorId = 2,
                            SpecializationId = 2
                        });
                });

            modelBuilder.Entity("HealthcareClinic.API.Models.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("HealthcareClinic.API.Models.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPRNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientReferenceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CPRNumber = "990123456",
                            Name = "Ali Mansoor",
                            PatientReferenceNumber = "REF-2026-ALI",
                            UserId = 5
                        },
                        new
                        {
                            Id = 2,
                            CPRNumber = "880234567",
                            Name = "Mariam Hassan",
                            PatientReferenceNumber = "REF-2026-MAR",
                            UserId = 6
                        });
                });

            modelBuilder.Entity("HealthcareClinic.API.Models.Entities.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VisitRecordId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VisitRecordId");

                    b.ToTable("Prescriptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Dosage = "5mg",
                            Duration = "30 days",
                            Frequency = "Once daily",
                            MedicationName = "Amlodipine",
                            VisitRecordId = 1
                        });
                });

            modelBuilder.Entity("HealthcareClinic.API.Models.Entities.Specialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Specializations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Heart and cardiovascular care.",
                            Name = "Cardiology"
                        },
                        new
                        {
                            Id = 2,
                            Description = "General health checkups and common illness treatment.",
                            Name = "General Practice"
                        });
                });

            modelBuilder.Entity("HealthcareClinic.API.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "hadi@clinic.com",
                            Name = "Hadi Al-Mansoori",
                            PasswordHash = "$2a$11$JuK.0gfwfl//T8amWFACiuCqSXEEAixxeJTz0OACExeoQvNf.W/3O",
                            Role = "ClinicManager"
                        },
                        new
                        {
                            Id = 2,
                            Email = "sarah.ahmed@clinic.com",
                            Name = "Dr. Sarah Ahmed",
                            PasswordHash = "$2a$11$JuK.0gfwfl//T8amWFACiuCqSXEEAixxeJTz0OACExeoQvNf.W/3O",
                            Role = "Doctor"
                        },
                        new
                        {
                            Id = 3,
                            Email = "khalid.nasser@clinic.com",
                            Name = "Dr. Khalid Nasser",
                            PasswordHash = "$2a$11$JuK.0gfwfl//T8amWFACiuCqSXEEAixxeJTz0OACExeoQvNf.W/3O",
                            Role = "Doctor"
                        },
                        new
                        {
                            Id = 4,
                            Email = "fatima@example.com",
                            Name = "Fatima Al-Zayed",
                            PasswordHash = "$2a$11$JuK.0gfwfl//T8amWFACiuCqSXEEAixxeJTz0OACExeoQvNf.W/3O",
                            Role = "Receptionist"
                        },
                        new
                        {
                            Id = 5,
                            Email = "ali@example.com",
                            Name = "Ali Mansoor",
                            PasswordHash = "$2a$11$JuK.0gfwfl//T8amWFACiuCqSXEEAixxeJTz0OACExeoQvNf.W/3O",
                            Role = "Patient"
                        },
                        new
                        {
                            Id = 6,
                            Email = "mariam@example.com",
                            Name = "Mariam Hassan",
                            PasswordHash = "$2a$11$JuK.0gfwfl//T8amWFACiuCqSXEEAixxeJTz0OACExeoQvNf.W/3O",
                            Role = "Patient"
                        });
                });

            modelBuilder.Entity("HealthcareClinic.API.Models.Entities.VisitRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("DoctorNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PrescribedTreatment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("VisitRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentId = 1,
                            Diagnosis = "Mild hypertension detected. Monitoring recommended.",
                            DoctorNotes = "Patient advised to reduce salt intake and exercise regularly.",
                            PrescribedTreatment = "Lifestyle changes and follow-up in 4 weeks.",
                            VisitDate = new DateTime(2026, 6, 1, 9, 30, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HealthcareClinic.API.Models.Entities.Appointment", b =>
                {
                    b.HasOne("HealthcareClinic.API.Models.Entities.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthcareClinic.API.Models.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthcareClinic.API.Models.Entities.Doctor", b =>
                {
                    b.HasOne("HealthcareClinic.API.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthcareClinic.API.Models.Entities.DoctorSchedule", b =>
                {
                    b.HasOne("HealthcareClinic.API.Models.Entities.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("HealthcareClinic.API.Models.Entities.DoctorSpecialization", b =>
                {
                    b.HasOne("HealthcareClinic.API.Models.Entities.Doctor", "Doctor")
                        .WithMany("DoctorSpecializations")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthcareClinic.API.Models.Entities.Specialization", "Specialization")
                        .WithMany("DoctorSpecializations")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("HealthcareClinic.API.Models.Entities.Notification", b =>
                {
                    b.HasOne("HealthcareClinic.API.Models.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthcareClinic.API.Models.Entities.Patient", b =>
                {
                    b.HasOne("HealthcareClinic.API.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthcareClinic.API.Models.Entities.Prescription", b =>
                {
                    b.HasOne("HealthcareClinic.API.Models.Entities.VisitRecord", "VisitRecord")
                        .WithMany("Prescriptions")
                        .HasForeignKey("VisitRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VisitRecord");
                });

            modelBuilder.Entity("HealthcareClinic.API.Models.Entities.VisitRecord", b =>
                {
                    b.HasOne("HealthcareClinic.API.Models.Entities.Appointment", "Appointment")
                        .WithOne("VisitRecord")
                        .HasForeignKey("HealthcareClinic.API.Models.Entities.VisitRecord", "AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthcareClinic.API.Models.Entities.Doctor", null)
                        .WithMany("VisitRecords")
                        .HasForeignKey("DoctorId");

                    b.HasOne("HealthcareClinic.API.Models.Entities.Patient", null)
                        .WithMany("VisitRecords")
                        .HasForeignKey("PatientId");

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("HealthcareClinic.API.Models.Entities.Appointment", b =>
                {
                    b.Navigation("VisitRecord");
                });

            modelBuilder.Entity("HealthcareClinic.API.Models.Entities.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("DoctorSpecializations");

                    b.Navigation("VisitRecords");
                });

            modelBuilder.Entity("HealthcareClinic.API.Models.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("VisitRecords");
                });

            modelBuilder.Entity("HealthcareClinic.API.Models.Entities.Specialization", b =>
                {
                    b.Navigation("DoctorSpecializations");
                });

            modelBuilder.Entity("HealthcareClinic.API.Models.Entities.User", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("HealthcareClinic.API.Models.Entities.VisitRecord", b =>
                {
                    b.Navigation("Prescriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
